export const users = [
  {
    id: 1,
    firstName: "Generic",
    lastName: "User",
    email: "generic.user@lau.edu",
    rating: 4.6,
    completedRides: 2, // Should be fetched from SQL (join or union)
    numberOfReviews: 4
  },
  {
    id: 2,
    firstName: "Khaled",
    lastName: "Jalloul",
    email: "khaled.jalloul@lau.edu",
    rating: 3.7,
    completedRides: 0,
    numberOfReviews: 0
  },
  {
    id: 3,
    firstName: "Hadi",
    lastName: "Youness",
    email: "hadi.youness@lau.edu",
    rating: 4.2,
    completedRides: 1,
    numberOfReviews: 2
  },
  {
    id: 4,
    firstName: "Sara",
    lastName: "Al Arab",
    email: "sara.alarab@lau.edu",
    rating: 4,
    completedRides: 2,
    numberOfReviews: 3
  },
];

export const rides = [
  {
    id: 1,
    dateOfDeparture: new Date(),
    departureCoordinates: { latitude: 34.1155614, longitude: 35.6744347 },
    departureLocation: "LAU Byblos",
    destinationCoordinates: { latitude: 33.7821927, longitude: 35.5312037 },
    destinationLocation: "Bchamoun",
    route: "kefoEetvxEoBvCRv@p@rBXnBFrGd@lBU|Cm@pBZn@?@?BBDDBRl@w@tBsJvPaC~DoFxEmBrI_BrBcBbE_CdKm@zI?LS~Dh@~IfEx@p@P?t@@n@FvEv@Kx@b@bAOv@QpE_@tGWzAEEc@pLeAfC[jRuCd[y@tr@g@xIFhFn@rIfCdKrBzKMbI@~H|BpIlCrGVtFk@dFOtEbAvDdCnQvPlMzKdFhCvGnAdBLfHUpJiCnNwFfFw@lC?vJdCxMdEfGtCxDxF`ExJtAjBnDbDlFdCzGfBlHjCzGlDzSnOjG|EpNpKrNfIvGbB`HXdGoAvBqArDyDxCuC|EuBvCWnEXpHvAfFRlE]xMcCvJgChFcC~DcD`FoGbCyFjBsInAoa@\\mF`@oAh@kAxOoNbHeEtEkAtFEjKrAhRdC`QjEhl@dRnm@lWrEjC`EzDjM`PdQtT|DlGxAlF^lDE~F_B|JiD~R_@zEL|D|@nEtIvO|GfPhCdFpJjJrHdHbHnD`k@`WnK|E~M|LlKfL`CdGfBjOd@xDjBtC`HvCvGjBrGTdQ?`NlBfIpB~OnB`f@xHzUbDlN|Dbm@~KpFnArIpDpItC|OzH~TbM`HfGdLzKxp@dq@lI~InB`EZ`AtAtMvEva@fEh^d@vIsFf^aIte@wB|KiBUgJuBcLeBDd@dZhG~NnDlHnDvJhFvKjDhLz@xKlAxYlGrIjCnKjGnCp@pCCtIwDtLyFnBOrPfAx^`CzDF~Cm@~CuAdLaJnNiKzBNnDZtEBf@@?h@@Z@dAJf@`AdAbAhCZ`F`@v@t@bAfBhF|@z@lADl@XbBChAFh@e@`ASjAADb@GbASbAGd@Kl@nH[hG[vBKvHc@nMo@hGlBfD`@rD@bJrAnRxA~FPjD]dCiAxAt@tDxC~Cd@xDa@tNlBrBG~As@vCsGr@[zC`@|@`@pAsAtAoAzDiD|M}LhFyE`@[D{A_@wCOcCh@iA|BoAvGeDpE_CnC}@tBAJg@A{@BQr@p@~@vAN\\B~@[xA@bAVr@dAh@rAAzA_Av@wDrEsOt@cGhJwFpGaElDqGfBsEv@u@lAV|A\\^e@^sAn@gBl@eAvCTp@B~A}@vHaFxAEhCr@z@v@P|AHvFN`GP`CfCh@lCIpAaApDaHlE_B`DgEdDGjEsApDaF`Au@l@z@r@xFjAdITfDMtDh@|Cb@dBl@l@~@LdFs@xD?jAjBhDnDnAnDr@\\p@Zp@zAj@bDfBj@jAMn@m@x@{@XFEbD~@pBhAjDaA~Du@xJMrGb@nAAd@[\\c@h@m@LGT",
    numberOfSeats: 3,
    pricePerRider: 1,
    driverID: 3,
  },
  {
    id: 2,
    dateOfDeparture: new Date(),
    departureCoordinates: { latitude: 33.7821927, longitude: 35.5312037 },
    departureLocation: "Bchamoun",
    destinationCoordinates: { latitude: 34.1155614, longitude: 35.6744347 },
    destinationLocation: "LAU Byblos",
    route: "iaemEytzwEvA_ANi@`@Ig@iAYcCXcDh@gIfAiEB_Bs@cBqAaCHeDWUq@h@yAhAmBAc@[i@cCi@uBm@aAQIEBw@Ia@}@aAqCqBiBy@oAa@q@aCWcHbA_AIq@i@Oa@aAaHByFcAsHgBqJy@TiD~EeEjBqDBuBbCgB`BqCr@yCnFeBzBeB`@wCc@s@KGkAQyBGmC?aGi@uCeBiAsCO{EhCiDdCeATmC_@cAt@yApE_@d@k@E_Co@_AdAq@lB}C|G}DpDiMvGm@r@k@pEkErOaAlEe@z@{Bj@eAWUSYm@EcAZwCcAmBaAcACn@C`AoADgCXyE|BeDh@_EfBaA`@e@p@WzAG~Ab@jCN~BY|@uAlAyFfFqEfEmLhKkBjBmBu@{BIq@h@{AhE_AbAsBn@qBIsF}@eI[qCHsD}AsCkCmC~@gIl@aU_BwFaAcHe@uCI{GwBuDCyGTqEZa@BH_AHcBMwAX}Ez@}D`BwE\\y@\\{@Y]{@kAi@m@wAm@Kc@}B_DqBqB}@[oNUkOu@}@SaC_Bu@?{B`BwAb@aAF_HnFmJfGwRzOgFzBsDJmCg@}F{@kHh@__@_CsFfAuP`JaFX{DsA}KeGwYqHeQqCqKc@uFaAwFiBaKyFqHuDuEsAwEgAc@}@pDyU|Jao@jAyKg@kI{LghAw@yFcAmCqC_E{FiGuVaWyNaOmXsWmHeGmL_HwM}GaJuDuHuCoLiE_\\iGiIwAwFcAmQuEmf@eHm\\gFeLgBgImBqG}@wGW{JJoFM_IyBiCu@uC{AwAqB]gBSeFc@mEqB}GqCmF{H}IsJsIiIcFkN_GwUmKsVyLsRaR_FsLwLwUyBgFe@eDE}DfAwH~CeQnAqJGwEm@aFk@sBuCqFsU}YuJ{LoGwFkd@mSyQsH}UoHwKiDsUoGca@iFyFVkEvAcGvDoJxI_EdEg@hAi@lD[bKm@dUeBdLwFbLoGhGwFrCyKzCwRzC_GSoHuAsE]kDZmFdCiErEiF|DmAf@gG`@gDS_IqBoH_EeN_K}[oVwOaJ}O_F{GgDiDwD_FqLmD}E_BgAqL}DmP_FsCKgE^}MzEkI~CuGt@wEAoGgA{DeBuGyEwMiM{M{LoE_BeEOmGj@eIDeG}AwGkCkEu@wKJeFJaKcBwJuCoEq@gQSiWVkj@n@yJp@wVzDyVpA}EAqCF}AOm@uBk@mBu@}EM{C^qEDMBECM`@yHfBsJtA{DjBgC|@mCh@yDjDsDrCoCjJgQpCmEIuAGUE?e@a@Nc@Ni@R}@PkBEi@a@eBEwGgAcFGmA~AoBAC",
    numberOfSeats: 4,
    pricePerRider: 2,
    driverID: 4,
  },
  {
    id: 3,
    dateOfDeparture: new Date(),
    departureCoordinates: { latitude: 34.1155614, longitude: 35.6744347 },
    departureLocation: "AUB Main Gate",
    destinationCoordinates: { latitude: 33.7821927, longitude: 35.5312037 },
    destinationLocation: "Mazraa, Beirut",
    route: "g~{mEycqwEEv@@ZDTr@fGb@zD\\hEVrB`@vCRtAVjCD`ALt@XpD`@hDN|AId@[f@GVC|ADl@Jt@Vl@FJDDFFPFJBRAJCt@c@PGTAD?^@?v@@fA@`A@^b@Bb@@nCLpDl@L?R@RC`B_Ax@WjAKb@JRXNh@VzAP~@NXHFTDFEHITo@t@qEJq@Ji@V]dBgABAPG`@GpE[dAKfAYb@UdA{@rA{A^a@j@]v@a@nCwApAy@|@cAz@sAb@iAH_@ToAb@eDLm@N]Zi@b@_@zCwARQNWRa@`@sAR_AL{@?WPy@h@wB|@}DpA{Gj@kC~@_FRqAXuCp@wGj@_FPcA\\qCb@}B\\kBBKUEo@UyBgAaAe@j@iB`@sAt@}Bz@yCl@yBw@[s@QqBs@qAk@`AoEJg@Je@THpAd@m@zB",
    numberOfSeats: 3,
    pricePerRider: 1.5,
    driverID: 1,
  },
  {
    id: 4,
    dateOfDeparture: new Date(),
    departureCoordinates: { latitude: 34.1155614, longitude: 35.6744347 },
    departureLocation: "South Lebanon",
    destinationCoordinates: { latitude: 33.7821927, longitude: 35.5312037 },
    destinationLocation: "LAU Beirut",
    route: "gqxkEut|vEvDyCRAl@r@b@Tn@GZQPWHi@KeAW[oAg@_Bc@yA_@}ASoE@gEb@aGd@wE@aDOmBWaGiAeB]q@Ai@Hg@@e@GuP_FgLiDo@q@M[OWWOWBOHKDc@?_McFmYoL}Ac@eJ{AeD[uCGOEg@u@QGe@F]VkBIeAYgDIeB?qGViACqA]kIwCq@Eu@Fg@Ri@f@sA|Aa@P]B_@Bu@IeKcBqIqBcNuCkIuAeAIwBc@{@_@_BmAwAkBcBsBo@e@cAa@iAYeAGgBDwEdAoBFgDQmDw@qBaAiCiCkAcBm@mAcAwCcAuFaAcI{AiNmAyIO}@y@mCqAaD{AcCmAuAoB_ByCgBmAe@aCq@yAQeDKsE\\eD~@wEnBmDdBoEbBiEpAcF`AkPbBiKb@cKMuCFaDL{E?aJSuNg@wa@wAiHTyO`DeFlAmCVuAB}AKgCi@sC{A_A{@mAaBiAcCw@_DYqCw@qM_A{KoCiVyBuPeAmEkB{EmBgDiLiQgBqBqAmAqBsAuIuDgDsAyRcIoOoGmAa@sEeA{CS}DCiFDgLDwGLuDXuBb@{Ah@yAz@eDvCiCzDiBzCoBvB{AnAmAp@yAj@qBb@qCNcAAkCU_ASqCeAcGwCmDcA}BScAC_DP_ANuBl@wGjCqElAuAHuBGiCUgAWiC{@gBgAcC_CaAsAsAqCeEsKoDmJyDgPaEmQyByHmB}DmBwCsBeC_CiB_DoBaDeBqGiEwE_FkByBeKmL}BmC_J}IuEeDoBeAyCiAsEsAcDw@mIiBiFy@mHu@aReAqSeAce@gC{V{AsMa@eGD_ERcYrBgMbAeU|A{BAsBOkCk@{Am@gK{FyHoE}MgH{R}JqEgCwC{ByI_Je[o\\eB}AuBeB{CkBwHkEqOwI}JqFmw@kc@aOkI_SiL}H{D}Cw@}BWqCBkEd@yEZqAKeA]cIwFyn@id@_t@yg@wv@mi@gOcKk@[}@UqA@iBf@uDhC{@p@aAlAiAfBwC|F{CdFyChDeAvBk@fBwAtFgAxCeC|Fq@jAy@hA}AdAq@ZkAPgC?aGk@sAIwA@kDTaFn@qD^wDRsRX_QTcPZuJJcFHiECcRe@sKe@wCSuC@kH[sUaAye@qBwHOoEMeNA{A@_AKaBY{JuD{TcIeI}CoHgCmFmBcOaFyD}Ag@EgAHi@^Wn@GrAIb@cCvJsAhCwAtAo@tAMdBL~Dz@lIJxBDpGJjTD~DfAExFMv@LbD~ETpARdANv@s@CgACTdCJbD?fBAfEBd@BDl@r@SZs@|Au@|Bk@tCY|DMtDEhBd@PRH",
    numberOfSeats: 3,
    pricePerRider: 2,
    driverID: 1,
  },
  {
    id: 5,
    dateOfDeparture: new Date(),
    departureCoordinates: { latitude: 34.1155614, longitude: 35.6744347 },
    departureLocation: "LAU Byblos",
    destinationCoordinates: { latitude: 33.7821927, longitude: 35.5312037 },
    destinationLocation: "Bchamoun",
    route: "kefoEetvxEoBvCRv@p@rBXnBFrGd@lBU|Cm@pBZn@?@?BBDDBRl@w@tBsJvPaC~DoFxEmBrI_BrBcBbE_CdKm@zI?LS~Dh@~IfEx@p@P?t@@n@FvEv@Kx@b@bAOv@QpE_@tGWzAEEc@pLeAfC[jRuCd[y@tr@g@xIFhFn@rIfCdKrBzKMbI@~H|BpIlCrGVtFk@dFOtEbAvDdCnQvPlMzKdFhCvGnAdBLfHUpJiCnNwFfFw@lC?vJdCxMdEfGtCxDxF`ExJtAjBnDbDlFdCzGfBlHjCzGlDzSnOjG|EpNpKrNfIvGbB`HXdGoAvBqArDyDxCuC|EuBvCWnEXpHvAfFRlE]xMcCvJgChFcC~DcD`FoGbCyFjBsInAoa@\\mF`@oAh@kAxOoNbHeEtEkAtFEjKrAhRdC`QjEhl@dRnm@lWrEjC`EzDjM`PdQtT|DlGxAlF^lDE~F_B|JiD~R_@zEL|D|@nEtIvO|GfPhCdFpJjJrHdHbHnD`k@`WnK|E~M|LlKfL`CdGfBjOd@xDjBtC`HvCvGjBrGTdQ?`NlBfIpB~OnB`f@xHzUbDlN|Dbm@~KpFnArIpDpItC|OzH~TbM`HfGdLzKxp@dq@lI~InB`EZ`AtAtMvEva@fEh^d@vIsFf^aIte@wB|KiBUgJuBcLeBDd@dZhG~NnDlHnDvJhFvKjDhLz@xKlAxYlGrIjCnKjGnCp@pCCtIwDtLyFnBOrPfAx^`CzDF~Cm@~CuAdLaJnNiKzBNnDZtEBf@@?h@@Z@dAJf@`AdAbAhCZ`F`@v@t@bAfBhF|@z@lADl@XbBChAFh@e@`ASjAADb@GbASbAGd@Kl@nH[hG[vBKvHc@nMo@hGlBfD`@rD@bJrAnRxA~FPjD]dCiAxAt@tDxC~Cd@xDa@tNlBrBG~As@vCsGr@[zC`@|@`@pAsAtAoAzDiD|M}LhFyE`@[D{A_@wCOcCh@iA|BoAvGeDpE_CnC}@tBAJg@A{@BQr@p@~@vAN\\B~@[xA@bAVr@dAh@rAAzA_Av@wDrEsOt@cGhJwFpGaElDqGfBsEv@u@lAV|A\\^e@^sAn@gBl@eAvCTp@B~A}@vHaFxAEhCr@z@v@P|AHvFN`GP`CfCh@lCIpAaApDaHlE_B`DgEdDGjEsApDaF`Au@l@z@r@xFjAdITfDMtDh@|Cb@dBl@l@~@LdFs@xD?jAjBhDnDnAnDr@\\p@Zp@zAj@bDfBj@jAMn@m@x@{@XFEbD~@pBhAjDaA~Du@xJMrGb@nAAd@[\\c@h@m@LGT",
    numberOfSeats: 3,
    pricePerRider: 1,
    driverID: 4,
  }
];

export const stopRequests = [
  {
    id: 1,
    requestStatus: "Pending",
    location: { latitude: 33.7821927, longitude: 35.5312037 },
    note: "Pls pick me up",
    studentID: 1,
    rideID: 1,
    dateOfRequest: new Date(),
  },
  {
    id: 2,
    requestStatus: "Approved",
    location: { latitude: 33.7821927, longitude: 35.5312037 },
    note: "Pls pick me up",
    studentID: 1,
    rideID: 2,
    dateOfRequest: new Date(),
  },
  {
    id: 3,
    requestStatus: "Approved",
    location: { latitude: 33.7821927, longitude: 35.5312037 },
    note: "Pls pick me up",
    studentID: 2,
    rideID: 2,
    dateOfRequest: new Date(),
  },
  {
    id: 4,
    requestStatus: "Approved",
    location: { latitude: 33.7821927, longitude: 35.5312037 },
    note: "Pls pick me up",
    studentID: 3,
    rideID: 2,
    dateOfRequest: new Date(),
  },
  {
    id: 5,
    requestStatus: "Approved",
    location: { latitude: 33.7821927, longitude: 35.5312037 },
    note: "Pls pick me up",
    studentID: 4,
    rideID: 3,
    dateOfRequest: new Date(),
  },
];
